@startuml
left to right direction

actor "操作员A" as OperatorA

rectangle "PA业务管理系统 - 寄卖清单竞拍 - 清单列表" {
  OperatorA --> (清单筛查)
  OperatorA --> (清单发布)
  OperatorA --> (批量导出指导清单)
  OperatorA --> (导出放弃清单及其原因)
  OperatorA --> (批量作废)
  OperatorA --> (进入详情)


  (进入详情) --> (编辑和查看基本资料)
  (进入详情) --> (编辑和查看审核记录)
  (进入详情) --> (重新分配)
  (进入详情) --> (重新发布)
  (进入详情) --> (清单放弃)
  (进入详情) --> (导出清单下载记录)

  (进入详情) --> (查看发布轮次)
  (查看发布轮次) --> (得分详情)
  (查看发布轮次) --> (供应商分数详情)

}

note right of OperatorA
  职责：
  - 管理清单信息
  - 参与发布清单
  - 分析并查看放弃清单原因
  - 作废清单
  - 重新发布清单
  - 指定清单寄卖商
end note


@enduml
