@startuml

[*] --> 创建寄卖商清单 : 自动组单

创建寄卖商清单 : 新建-10

创建寄卖商清单 -down-> 寄卖清单待发布 : 审核通过后清单待发布
创建寄卖商清单 -left-> 寄卖清单发布中 : 自动审核通过直接发布
寄卖清单待发布 : 待发布-20


寄卖清单待发布 -left-> 寄卖清单发布中 : <color #red>人工分配寄卖清单发布开始日期和结束日期\n指定寄卖商投标
寄卖清单发布中 : 发布中-30



寄卖清单发布中 -down-> 寄卖清单待分配 : 发布时间结束后\n<color #red>不管有无寄卖商投标，寄卖清单都为待分配\n寄卖商停止参与投标
寄卖清单待分配 : 待分配-40


寄卖清单待分配 -up-> 寄卖清单发布中 : 发布时间结束后\n<color #red>没有寄卖商参与投标，重新发布


寄卖清单待分配 -down-> 寄卖清单分配完成 : 发布时间结束后\n<color #red>有寄卖商参与投标，根据分数规则分配第一名寄卖商
寄卖清单分配完成 : 分配完成-50

寄卖清单分配完成 -down-> 寄卖清单已作废 : 寄卖商不想要了，要弃单\n取消该寄卖商的接单资格，寄卖单作废

寄卖清单分配完成 -down-> 寄卖清单已作废 : 寄卖商指定错误\n作废该清单

寄卖清单分配完成 -down-> 寄卖清单已作废 : 寄卖商超过7天未上传采购凭证，作废该清单

寄卖清单分配完成 -up-> 寄卖清单发布中 : 寄卖商超过7天未上传采购凭证，重新发布

寄卖清单分配完成 -left-> 寄卖清单结束 : 采购商上传凭证，来货，寄卖单最终结束
寄卖清单结束 : 清单结束-60

寄卖清单发布中 -down-> 寄卖清单已作废 : 发布时间结束后，<color #red>无寄卖商参与投标\n根据配置，作废QD单,转自营，无需新增轮次
寄卖清单已作废 : 已作废-100


寄卖清单已作废 -up-> 寄卖清单发布中 : 对已作废的寄卖清单\n回收清单，增加轮次，重新发布

寄卖清单待发布 -down-> 寄卖清单已作废 : 发现寄卖清单有问题，直接作废，重新生产新的寄卖清单


@enduml