@startuml

package "product_operation_js_angular5"{
    [资料编辑-保存-修改属性更新]
    [资料编辑-保存-修改侵权禁词]
    [批量资料编辑]
}

package "RocketMQ"{
    [资料翻译+禁词检查MQ]
}

package "pa-biz-application"{
    [处理资料变更单据服务]
}
package "translation_nodejs_app"{
	[谷歌翻译]
}
package "pa-biz-service"{
    [初始化创建资料变更单据]
    [更新资料变更单据]
    [资料翻译+禁词检查+长度校验服务]
}



package "product_operation_listing_management_nodejs_app"{
	[updateProductSku接口更新资料服务]
	[资料变更前后差异比对服务]
	[禁词检查]
}


package "platform-config-service"{
	[配置]
}

package "platform-message-service"{
	[钉钉通知]
}





'DataAccess - [First Component]
'[First Component] ..> HTTP : use
[资料编辑-保存-修改属性更新] -down-> [updateProductSku接口更新资料服务]

[资料编辑-保存-修改侵权禁词] -down-> [updateProductSku接口更新资料服务]

[批量资料编辑] -.down.-> [updateProductSku接口更新资料服务]

[updateProductSku接口更新资料服务] -.down.-> [资料变更前后差异比对服务] : <color #red><b>1、</b></color>更新前资料和更新后资料更新对比\n返回对应渠道的变更数据

[资料变更前后差异比对服务] -down-> [处理资料变更单据服务] : <color #red><b>2、</b></color>根据渠道及配置初始化单据

[配置] -left-> [处理资料变更单据服务] : 获取配置，通过配置决定单据的渠道，属性变更内容等

[处理资料变更单据服务] -down-> [初始化创建资料变更单据] : <color #red><b>3、</b></color>创建单据<color #red>初始状态 = 10(新建) </color>

[初始化创建资料变更单据] -up-> [资料翻译+禁词检查MQ] : <color #red><b>4、</b></color>初始化单据后，发起mq，对单据属性做谷歌翻译和禁词检查

[资料翻译+禁词检查MQ] -right-> [资料翻译+禁词检查+长度校验服务] : <color #red><b>5、</b></color>MQ消费

[资料翻译+禁词检查+长度校验服务] -right-> [更新资料变更单据] : <color #red><b>6、</b></color>首先开始资料翻译,<color #red>更新状态 = 20(翻译中)</color>

[更新资料变更单据] -down-> [谷歌翻译] : <color #red><b>7、</b></color>调用资料翻译接口

[谷歌翻译] .up.> [资料翻译+禁词检查+长度校验服务] : <color #red><b>8、</b></color>返回翻译结果

[资料翻译+禁词检查+长度校验服务] -right-> [更新资料变更单据] : <color #red><b>9、</b></color><color #red>更新状态 = 30(翻译完成)</color>

[更新资料变更单据] -left-> [禁词检查] : <color #red><b>10、</b></color>调用禁词检查接口

[禁词检查] -down-> [资料翻译+禁词检查+长度校验服务] : <color #red><b>11、</b></color>返回禁词检查结果

[资料翻译+禁词检查+长度校验服务] -right-> [更新资料变更单据] : <color #red><b>12、</b></color><color #red>更新状态 = 40(禁词检查完成)</color>




@enduml