@startuml


package "RocketMQ"{
	[忽略和创建资料变更单据]
	[更新资料变更单据和更资料]
}

package "platform-sms-support-application"{
	[处理资料变更单据]
    []
    []
}
'platform-sms-support-application

package "platform-item-service"{
	[PT数据结果版本服务]
	[PT单据服务]
}

package "product_operation_listing_management_nodejs_app"{
	[PT关系映射表配置服务]
}

package "poms_listing_nestjs"{
	[PT原数据map表服务]
	[推荐PT表服务]
}

package "新前端web"{
	[小语种资料变更管理页面]
}

package "platform-message-service"{
	[钉钉通知]
}





'DataAccess - [First Component]
'[First Component] ..> HTTP : use

[解析API原数据] ..> [PT数据结果版本应用] : MQ消费
[PT数据结果版本应用] --> [PT数据结果版本服务] : 新增/更新PT数据结果版本
[PT数据结果版本应用] --> [PT单据服务] : 忽略单据


[新增/忽略PT单据应用] --> [PT原数据map表服务]
[新增/忽略PT单据应用] --> [PT关系映射表配置服务]
[新增/忽略PT单据应用] --> [推荐PT表服务]
[新增/忽略PT单据应用] --> [钉钉告警通知]
[新增/忽略PT单据应用] --> [PT单据服务] : 新增单据

[amazon目录变更管理页面] --> [新增/更新推荐PT应用] : 更新/忽略单据

[新增/更新推荐PT应用] --> [PT原数据map表服务]
[新增/更新推荐PT应用] --> [PT关系映射表配置服务]
[新增/更新推荐PT应用] --> [推荐PT表服务] : 新增/更新推荐PT
[新增/更新推荐PT应用] --> [钉钉告警通知]

@enduml