@startuml
!theme plain

package "RocketMQ"{
    [资料翻译+禁词检查MQ]
    [导入批量审核更新MQ]
}

package "pa-biz-web"{
    [资料变更通知管理 - page]
    [资料变更通知管理 - 状态数量汇总]
    [资料变更通知管理 - 更新]
    [资料变更通知管理 - 忽略]
    [资料变更通知管理 - 导出查询结果]
    [资料变更通知管理 - 导入批量审核更新]
    [资料变更通知管理 - 批量审核记录]
    [资料变更通知管理 - 查看单据日志]
    [下载]
}


package "pa-biz-application"{
    [查询资料变更单据]
    [资料变更单据各状态汇总]
    [处理资料变更单据应用]
    [处理excel表格内容]
    [导入批量审核更新接口]
    [查询批量导入审核接口]
}


package "pa-biz-service"{
    [查询资料变更单据服务]
    [资料变更单据各状态汇总服务]
    [处理资料变更单据服务]
    [更新资料变更单据]
    [更新sku资料]
    [禁词检查+长度校验服务]
    [处理资料变更导入审核服务]
}



package "product_operation_listing_management_nodejs_app"{
	[updateProductSku接口更新资料服务]
	[禁词检查]
}

package "oss"{
    [oss文件]
}

package "ux168-log-service"{
	[ux日志系统]
}

package "platform-message-service"{
	[钉钉通知]
}





'DataAccess - [First Component]
'[First Component] ..> HTTP : use

[资料变更通知管理 - page] -down-> [查询资料变更单据]

[查询资料变更单据] -down-> [查询资料变更单据服务]

[资料变更通知管理 - 状态数量汇总] -down-> [资料变更单据各状态汇总]

[资料变更单据各状态汇总] -down-> [资料变更单据各状态汇总服务]

[资料变更通知管理 - 更新] -down-> [处理资料变更单据应用]

[处理资料变更单据应用] -down-> [资料翻译+禁词检查MQ]
[处理资料变更单据应用] -.down.-> [钉钉通知]

[资料翻译+禁词检查MQ] -down-> [处理资料变更单据服务]

[处理资料变更单据服务] -down-> [禁词检查+长度校验服务]

[禁词检查+长度校验服务] -down-> [禁词检查]

[禁词检查] -down-> [处理资料变更单据服务]

[处理资料变更单据服务] -down-> [更新sku资料]

[更新sku资料] -down-> [updateProductSku接口更新资料服务]

[处理资料变更单据服务] -down-> [更新资料变更单据]

[更新资料变更单据] -down-> [钉钉通知]

[资料变更通知管理 - 忽略] -down-> [处理资料变更单据应用]

[处理资料变更单据应用] -down-> [处理资料变更单据服务]


[资料变更通知管理 - 导出查询结果] -down-> [查询资料变更单据]

[查询资料变更单据服务] -down-> [处理excel表格内容]

[处理excel表格内容] -down-> [下载]

[资料变更通知管理 - 导入批量审核更新] -down-> [导入批量审核更新接口]

[导入批量审核更新接口] -down-> [导入批量审核更新MQ]

[导入批量审核更新MQ] -down-> [oss文件]

[oss文件] -down-> [处理excel表格内容]

[处理excel表格内容] -down-> [处理资料变更导入审核服务]

[处理资料变更导入审核服务] -down-> [禁词检查+长度校验服务]

[资料变更通知管理 - 批量审核记录] -down-> [查询批量导入审核接口]

[查询批量导入审核接口] -down-> [处理资料变更导入审核服务]

[资料变更通知管理 - 查看单据日志] -down-> [ux日志系统]

@enduml