@startuml
autonumber
title 资料变更单据创建

actor customer as Customer

box "应用项目"
    participant "product_operation_js_angular5"
    participant "pa-biz-application"
    participant "pa-biz-service"
    participant "product_operation_listing_management_nodejs_app"
    participant "translation_nodejs_app"
    participant "platform-config-service"
    participant "platform-message-service"
    participant "RocketMQ"
    participant "ux168-log-service"
    participant "mysql"
    participant "mongo"
end box

note left of customer
    customer进入page1或page2或者page3,
    保存资料后出都会进入到node1调用资料更新的接口
end note

customer -> "product_operation_js_angular5" : 进入page1或page2或page3
"product_operation_js_angular5" -> "product_operation_listing_management_nodejs_app" : 保存资料后进入node1调用资料更新接口，传递param1（旧数据）
"product_operation_listing_management_nodejs_app" -> "mongo" : 数据入库mongo1，获取param2（新数据）
"product_operation_listing_management_nodejs_app" -> "product_operation_listing_management_nodejs_app" : 对比param1和param2获取diff1
"product_operation_listing_management_nodejs_app" -> "pa-biz-application" : 以diff1和skuid作为入参进入app1

"pa-biz-application" -> "platform-config-service" : 调用config1获取配置参数
"pa-biz-application" -> "pa-biz-application" : 根据配置筛选数据，生成batch_no等构建object对象，设置apply_status = 10(新建)
"pa-biz-application" -> "pa-biz-service" : 调用service1，存储数据到sql1
"pa-biz-service" -> "pa-biz-service" : 返回主键id给service1
"pa-biz-service" -> "RocketMQ" : 调用mq1，初始化process_status = 10(等待翻译)

"RocketMQ" -> "pa-biz-service" : mq1接收主键id，进入service3的autoTranslationReferenceAttribute方法
"pa-biz-service" -> "pa-biz-service" : 更新process_status = 20(翻译中)
"pa-biz-service" -> "translation_nodejs_app" : 调用translation
alt 翻译失败（无值或调用失败）
    "translation_nodejs_app" -> "pa-biz-service" : 返回结果
    "pa-biz-service" -> "pa-biz-service" : 更新process_status = 40(翻译失败)
    "pa-biz-service" -> "RocketMQ" : 中止mq1
else
    "translation_nodejs_app" -> "pa-biz-service" : 返回结果
    "pa-biz-service" -> "pa-biz-service" : 更新process_status = 30(翻译完成)
    "pa-biz-service" -> "pa-biz-service" : 根据翻译后值等调service3的autoCheckTranslationReferenceAttributeForbidden
    "pa-biz-service" -> "pa-biz-service" : 更新process_status = 60(禁词检查中)
    "pa-biz-service" -> "product_operation_listing_management_nodejs_app" : 调用node3
    alt node3调用失败（超时等）
        "product_operation_listing_management_nodejs_app" -> "pa-biz-service" : 返回结果
        "pa-biz-service" -> "pa-biz-service" : 更新process_status = 80(禁词检查失败)
        "pa-biz-service" -> "RocketMQ" : 中止mq1
    else
        "product_operation_listing_management_nodejs_app" -> "pa-biz-service" : 返回forbidden_result
        "pa-biz-service" -> "pa-biz-service" : 遍历forbidden_result，记录禁词内容forbidden_value_list
        "pa-biz-service" -> "pa-biz-service" : 更新process_status = 70(禁词检查完成)
        "pa-biz-service" -> "pa-biz-service" : 调用service3的autoCheckAttributeLength
        "pa-biz-service" -> "pa-biz-service" : 更新process_status = 90(长度检查中)
        "pa-biz-service" -> "platform-config-service" : 从config1获取不同平台渠道的属性的长度条件配置
        alt 配置获取失败
            "platform-config-service" -> "pa-biz-service" : 返回结果
            "pa-biz-service" -> "pa-biz-service" : 更新process_status = 110(长度检查失败)
            "pa-biz-service" -> "RocketMQ" : 中止mq1
        else
            "platform-config-service" -> "pa-biz-service" : 返回长度配置
            "pa-biz-service" -> "pa-biz-service" : 比较长度得到attribute_value_length_result，更新process_status = 100(长度检查成功)
        end
    end
end

"pa-biz-service" -> "pa-biz-service" : 整理翻译内容、禁词内容、长度校验结果等，更新process_status = 120(全部检查完毕)，apply_status = 20(待审核)
"pa-biz-service" -> "pa-biz-service" : 调用service2的更新资料变更接口update，存储到sql1对应主键id的单据下
"pa-biz-service" -> "RocketMQ" : 中止mq1

@enduml