@startuml
title 资料变更单据创建
autonumber

actor customer

box "product_operation_js_angular5" #LightBlue
    participant page1 as "资料编辑-保存-修改属性更新"
    participant page2 as "资料编辑-保存-修改侵权禁词"
    participant page3 as "批量资料编辑"
end box

box "pa-biz-application" #LightGreen
    participant app1 as "处理资料变更单据服务"
end box

box "pa-biz-service" #LightYellow
    participant service1 as "初始化创建资料变更单据"
    participant service2 as "更新资料变更单据"
    participant service3 as "资料翻译+禁词检查+长度校验服务"
end box

box "product_operation_listing_management_nodejs_app" #LightCoral
    participant node1 as "updateProductSku接口更新资料服务"
    participant node2 as "资料变更前后差异比对服务"
    participant node3 as "禁词检查"
end box

box "translation_nodejs_app" #LightCyan
    participant translation as "翻译"
end box

box "platform-config-service" #LightGoldenRodYellow
    participant config1 as "配置"
end box

box "platform-message-service" #LightGray
    participant msg1 as "钉钉通知"
end box

box "RocketMQ" #LightPink
    participant mq1 as "资料翻译+禁词检查MQ"
end box

box "mysql" #LightSalmon
    participant sql1 as "sms_material_changed_notice_doc"
    participant sql2 as "sms_material_changed_batch_export_apply"
end box

box "mongo" #LightGreenYellow
    participant mongo1 as "product-sku"
    participant mongo2 as "product-sku-log"
end box

customer -> page1 : 进入资料编辑页面
customer -> page1 : 保存资料
page1 -> node1 : 调用更新资料接口
node1 -> mongo1 : 更新旧数据
node1 -> mongo1 : 新数据入库
node1 -> node2 : 对比旧数据与新数据
node2 -> node2 : 获取数据变更差异
node2 --> customer : 返回diff1

customer -> app1 : 调用处理资料变更单据服务(diff1)
app1 -> config1 : 获取配置参数
config1 --> app1 : 返回平台、渠道、属性

app1 -> app1 : 遍历diff1生成单据
app1 -> service1 : 存储单据到sql1
service1 --> app1 : 返回主键id

app1 -> mq1 : 初始化process_status = 10(等待翻译)
mq1 -> service3 : autoTranslationReferenceAttribute
service3 -> translation : 调用翻译
translation --> service3 : 返回翻译结果

alt 翻译成功
    service3 -> mq1 : 更新process_status = 30(翻译完成)
else 翻译失败
    service3 -> mq1 : 更新process_status = 40(翻译失败)
    
end

mq1 -> service3 : autoCheckTranslationReferenceAttributeForbidden
service3 -> node3 : 调用禁词检查
node3 --> service3 : 返回禁词结果

alt 禁词检查成功
    service3 -> mq1 : 更新process_status = 70(禁词检查完成)
else 禁词检查失败
    service3 -> mq1 : 更新process_status = 80(禁词检查失败)
    
end

mq1 -> service3 : autoCheckAttributeLength
service3 -> config1 : 获取属性长度条件配置
config1 --> service3 : 返回长度条件

alt 长度检查成功
    service3 -> mq1 : 更新process_status = 100(长度检查成功)
else 长度检查失败
    service3 -> mq1 : 更新process_status = 110(长度检查失败)
    
end

mq1 -> service2 : 更新资料变更的接口
service2 -> sql1 : 存储到sql1
sql1 --> service2 : 返回主键id

mq1 -> mq1 : 更新process_status = 120(全部检查完毕)
mq1 -> mq1 : 更新apply_status = 20(待审核)


@enduml
