@startuml
start

:用户D导入批量审核更新;
:上传OSS文件;
:调用导入批量审核更新接口;
:发起MQ;

:获取OSS文件解析文件内容;
:存储属性翻译数据;
:存储对应属性在单据上的主键ID、平台、操作人、OSS文件路径等;

if (存储数据失败?) then (是)
    :生成失败内容;
    :整理成xlsx文档;
    :上传OSS;
    :发送钉钉提醒用户报错;
    :贴上导入文件明细;
    :重新导入;
    stop
else (否)
    :文件解析成功;
    :数据记录成功;
    :发送钉钉通知提醒业务，查看进度;
    repeat
        :处理每一个单据;
        :执行流程B逻辑;

        if (单据检查不通过?) then (是)
        :记录检查不通过的原因;
        endif
    repeat while (还有单据待处理?)

    if (所有单据检查通过?) then (是)
        :根据SKU分组;
        :获取所有的变更属性;
        :批量更新SKU资料;

        repeat
            :更新每个SKU资料;
            if (更新成功?) then (是)
                :更新该SKU的属性的单据，审批状态 = <color:red>70</color>(已更新);
            else (否)
                :更新该SKU的属性的单据，审批状态 = <color:red>80</color>(更新失败);
            endif
        repeat while (还有SKU待更新?)
    else (否)
        :部分单据检查不通过，填充到xlsx单元格;
        :发送钉钉提醒报错;
    endif
endif

stop
@enduml
