@startuml

[*] --> 创建资料变更单据 : 资料编辑保存(不同类型)

创建资料变更单据 : 新建

创建资料变更单据 -down-> 处理变更属性MQ : 发MQ
处理变更属性MQ : 等待翻译


处理变更属性MQ -down-> 谷歌翻译 : 翻译内容
谷歌翻译 : 翻译中

谷歌翻译 -down-> 翻译结果1 : 成功
翻译结果1 : 翻译完成

谷歌翻译 -right-> 翻译结果2 : 失败
翻译结果2 : 翻译失败

翻译结果1 -down-> 禁词检查 : 禁词检查+长度限制
禁词检查 : 禁词检查中

禁词检查 -down-> 禁词检查结果1 : 成功
禁词检查结果1 : 禁词检查完成/待审核

禁词检查 -left-> 禁词检查结果2 : 失败
禁词检查结果2 : 禁词检查失败



[*] -up-> 更新资料变更单据 : 点击更新，发MQ

更新资料变更单据 : 等待禁词检查中

更新资料变更单据 -down-> 禁词检查


禁词检查结果1 -down-> 更新资料 : 更新资料
更新资料 : 已更新

[*] -right-> 忽略资料变更单据 : 点击忽略
忽略资料变更单据 : 已忽略


@enduml