@startuml
title ebay定价测试选择账号
autonumber
actor "customer" as customer

box "poms_js_web"
participant "设置ebay定价测试账号" as t1
end box

box "product_operation_listing_management_nodejs_app" #lightYellow
participant "ebay定价测试账号配置表" as t2
end box

box "poms_listing_nest" #lightYellow
participant "ebay定价测试" as t3
end box

customer -> t1 : 设置ebay定价测试账号
activate t1

t1 -> t2 : 获取ebay定价测试账号配置
activate t1
activate t2
t2 --> t1 : 返回数据

deactivate t1
deactivate t2
alt 有账号数据
t1 -> t1 : 列表展示账号
activate t1
t1 -> t3 : 选择账号，保存账号到定价设置表
activate t3
t3 --> t1 : 返回结果
deactivate t3
deactivate t1
t1 --> customer : 结束
end
deactivate t1
@enduml