@startuml
title 乐天在卖listing
autonumber
actor "customer" as customer

box "product_operation_js_angular5"
participant "乐天在卖listing" as p1
end box

box "product_operation_listing_management"
participant "乐天在卖listing" as n1
end box

box "db"
participant "rakuten_active_listing" as d1
end box

customer -> p1 : 访问乐天在卖listing页面
activate p1
p1 -> n1 : 查询乐天在卖listing数据<color #red>（可带variantid字段）
activate n1
n1 -> d1: 查询数据
activate d1
d1 --> n1 : 返回数据
deactivate d1
n1 --> p1 : 返回数据
p1 -> p1 : <color #red>variantid宽度完整显示，表格宽度调整为用户可自由拉伸
deactivate n1
p1 --> customer : 结束

@enduml