@startuml
title Amazon SP多种账号广告自动化 - 上架SKU
autonumber
actor "customer" as customer
box "product_operation_php_restful" #lightBlue

participant "UploadProcessAliyunController" as uploadPrecess
participant "PA自动化创建广告接口" as paAutoAmazonSP
participant "PA自动化创建广告数据校验接口" as paAutoAmazonSPValidate
end box

box "nsq_worker_nodejs_app" #lightYellow
participant "HK_Poms_Send_Amazon_Create_Sp" as HK_Poms_Send_Amazon_Create_Sp
end box

box "poms_selling_partner_php_restful" #lightGreen
participant "Amazon广告服务" as amazon
end box

box "database" #lightYellow
participant "mongoDB" as db
end box
customer -> uploadPrecess : 用户fba上架，触发上架接口
uploadPrecess -> db : 将要上架的sku数据保存到amazon_active_listing表(表示sku上架)
db --> uploadPrecess : 返回结果
alt sku上架成功，发起创建广告
uploadPrecess -> db : <color #red>读取广告账号表，查看需要创建广告的渠道账号
db --> uploadPrecess : 返回结果
alt 存在渠道账号
uploadPrecess -> HK_Poms_Send_Amazon_Create_Sp : 发起队列,创建auto类型广告
uploadPrecess -> HK_Poms_Send_Amazon_Create_Sp : 发起队列,创建manual asin类型广告
uploadPrecess -> HK_Poms_Send_Amazon_Create_Sp : 发起队列,创建manual category类型广告
end
end

group 创建广告
HK_Poms_Send_Amazon_Create_Sp o-> paAutoAmazonSP : 分发处理
paAutoAmazonSP -> paAutoAmazonSPValidate : 获取是否可以创建广告的校验结果<color #blue>(只能创建一种类型的广告)

alt 校验通过，创建广告
paAutoAmazonSPValidate -> db : 校验通过\n<color #red>根据渠道账号读取广告规则配置表
db --> paAutoAmazonSPValidate : 返回结果
paAutoAmazonSPValidate -> paAutoAmazonSPValidate : 整理和拼接广告配置信息

paAutoAmazonSPValidate --> paAutoAmazonSP : 返回渠道和账号的广告配置信息

paAutoAmazonSP -> db : 获取是否已存在广告
db --> paAutoAmazonSP : 返回是否存在广告结果


paAutoAmazonSP -> amazon : 创建/更新广告
amazon --> paAutoAmazonSP : 返回创建结果

alt 创建/更新广告成功
paAutoAmazonSP -> db : 创建/更新广告信息
db --> paAutoAmazonSP : 返回处理结果
end
end
end


@enduml