CREATE TABLE pa_walmart_weekly_data
(
    channel VARCHAR(225) NULL COMMENT '销售渠道',
    sellerId VARCHAR(225) NULL COMMENT '销售账号',
    scuId VARCHAR(225) NULL COMMENT 'scuId(上架编号)',
    skuId VARCHAR(225) NULL COMMENT 'skuId',
    cnCategory VARCHAR(225) NULL COMMENT '中文分类全路径',
    catLevel1 VARCHAR(225) NULL COMMENT '一级中文分类',
    catLevel2 VARCHAR(225) NULL COMMENT '二级中文分类',
    leafCategoryId VARCHAR(225) NULL COMMENT '末级分类ID',
    developerUserName VARCHAR(225) NULL COMMENT '开发人员',
    salesUserName VARCHAR(225) NULL COMMENT '销售人员',
    SZ_stockQty INT NULL COMMENT 'SZ仓在仓库存',
    SZ_onwayQty INT NULL COMMENT 'SZ仓补货在途数',
    US_04_stockQty INT NULL COMMENT 'US_04仓在仓库存',
    US_04_moveOnwayQty INT NULL COMMENT 'US_04仓移库在途数',
    US_WM1_stockQty INT NULL COMMENT 'US_WM1仓在仓库存',
    US_WM1_moveOnwayQty INT NULL COMMENT 'US_WM1仓移库在途数',
    W1_sold INT NULL COMMENT '历史第1周sold',
    W1_sales INT NULL COMMENT '历史第1周sales',
    W1_PL INT NULL COMMENT '历史第1周PL',
    W1_margin INT NULL COMMENT 'W1 Margin',
    W1_eff INT NULL COMMENT 'W1 销售效率',
    W2_sold INT NULL COMMENT '历史第2周sold',
    W2_sales INT NULL COMMENT '历史第2周sales',
    W2_margin INT NULL COMMENT 'W2 Margin',
    W2_PL INT NULL COMMENT '历史第2周PL',
    W2_eff INT NULL COMMENT 'W2 销售效率',
    W3_sold INT NULL COMMENT '历史第3周sold',
    W3_sales INT NULL COMMENT '历史第3周sales',
    W3_margin INT NULL COMMENT 'W3 Margin',
    W3_PL INT NULL COMMENT '历史第3周PL',
    W3_eff INT NULL COMMENT 'W3 销售效率',
    W4_sold INT NULL COMMENT '历史第4周sold',
    W4_sales INT NULL COMMENT '历史第4周sales',
    W4_margin INT NULL COMMENT 'W4 Margin',
    W4_PL INT NULL COMMENT '历史第4周PL',
    W4_eff INT NULL COMMENT 'W4 销售效率',
    W5_sold INT NULL COMMENT '历史第5周sold',
    W5_sales INT NULL COMMENT '历史第5周sales',
    W5_margin INT NULL COMMENT 'W5 Margin',
    W5_PL INT NULL COMMENT '历史第5周PL',
    W5_eff INT NULL COMMENT 'W5 销售效率',
    diffSold INT NULL COMMENT 'W1较W2的sold变化',
    diffSales INT NULL COMMENT 'W1较W2的sales变化',
    diffMargin INT NULL COMMENT 'W1较W2的Margin变化',
    diffPL INT NULL COMMENT 'W1较W2的PL变化',
    diffEff INT NULL COMMENT 'W1较W2的Eff变化',
    isOOS VARCHAR(225) NULL COMMENT '是否OOS：Yes、No',
    createdBy VARCHAR(225) NULL COMMENT '创建人',
    createdOn date NULL COMMENT '创建时间',
    modifiedBy VARCHAR(225) NULL COMMENT '修改人',
    modifiedOn date NULL COMMENT '修改时间'
) ENGINE = InnoDB DEFAULT CHARSET=utf8;